name: Multi-OS Testing - Jack MacKay

on:
  push:
    branches:
      - main

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Print start message
        run: echo "Testing on Ubuntu..."

      - name: Show OS information
        run: lsb_release -a || uname -a

      - name: Create test file
        run: echo "Ubuntu test by Jack MacKay" > test-ubuntu.txt

      - name: Display file contents
        run: cat test-ubuntu.txt

      - name: Print completion message
        run: echo "Ubuntu tests completed"

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Print start message
        run: echo "Testing on Windows..."

      - name: Show OS information
        run: systeminfo | findstr /B /C:"OS"

      - name: Create test file
        run: echo Windows test by Jack MacKay > test-windows.txt

      - name: Display file contents
        run: type test-windows.txt

      - name: Print completion message
        run: echo "Windows tests completed"